apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
spec:
  # Fixed because the host's CoreDNS forwards here.
  clusterIP: 10.43.0.53
  selector:
    app: blocky
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: http
      port: 4000
      protocol: TCP
      targetPort: http
