# Pinned to stable releases
FROM quay.io/fedora/fedora-bootc:44

LABEL org.opencontainers.image.title="mini-homelab"
LABEL org.opencontainers.image.description="Container services host for Raspberry Pi 4B"

# validates that the result is a well-formed, bootable bootc image.
# https://docs.fedoraproject.org/en-US/bootc/building-containers/#_linting
RUN bootc container lint
