# SPDX-License-Identifier: MPL-2.0

# Pinned to stable releases
FROM quay.io/fedora/fedora-bootc:44

LABEL org.opencontainers.image.title="mini-homelab"
LABEL org.opencontainers.image.description="Container services host for Raspberry Pi 4B"
LABEL org.opencontainers.image.source="https://github.com/149segolte/mini-homelab"

# Networking
RUN dnf -y install \
      NetworkManager-wifi \
      wpa_supplicant \
      brcmfmac-firmware \
      mt7xxx-firmware \
 && dnf clean all

 RUN dnf -y install firewalld && dnf clean all \
  && systemctl enable firewalld \
  && sed -i 's/^DefaultZone=.*/DefaultZone=drop/' /etc/firewalld/firewalld.conf

COPY files/ /

# validates that the result is a well-formed, bootable bootc image.
# https://docs.fedoraproject.org/en-US/bootc/building-containers/#_linting
RUN bootc container lint
