apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 2m
  retryInterval: 1m
  path: ./initialization/external-secrets/operator
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
