d /var/home/${ADMIN_USER} 0700 ${ADMIN_USER} ${ADMIN_USER} -
d /var/home/${ADMIN_USER}/.ssh 0700 ${ADMIN_USER} ${ADMIN_USER} -
f+ /var/home/${ADMIN_USER}/.ssh/authorized_keys 0600 ${ADMIN_USER} ${ADMIN_USER} - ${ADMIN_SSH_KEY}
