apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-pod-security-restricted
spec:
  failurePolicy: Fail
  background: false
  rules:
    - name: restricted
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - flux-system
                # Governed by restricted-technitium below.
                - technitium
      validate:
        failureAction: Enforce
        podSecurity:
          level: restricted
          version: latest

    - name: restricted-technitium
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - technitium
      validate:
        failureAction: Enforce
        podSecurity:
          level: restricted
          version: latest
          exclude:
            - controlName: "Host Ports"
              images:
                - "*technitium/dns-server*"
