apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-user-config
  namespace: technitium
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: technitium-user-config
  data:
    - secretKey: password
      remoteRef:
        key: technitium/initial-admin-password
    - secretKey: sso_client_id
      remoteRef:
        key: authelia/oidc/clients/technitium/id
    - secretKey: sso_client_secret
      remoteRef:
        key: authelia/oidc/clients/technitium/secret
