apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium
  namespace: technitium
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
