apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-github-token
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: glance-github-token
  data:
    - secretKey: token
      remoteRef:
        key: glance/github-token
