apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  releaseName: flux-operator
  chart:
    spec:
      chart: flux-operator
      version: "0.59.*"
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
  values:
    web:
      enabled: true
      config:
        baseURL: https://flux.${DOMAIN}
        authentication:
          type: Anonymous
          anonymous:
            username: flux-web-anonymous
            groups:
              - flux-web-viewers
      rbac:
        createRoles: true
        createAggregation: true
      userActions:
        access: Impersonated
      ingress:
        enabled: true
        className: traefik
        hosts:
          - host: flux.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
