apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: node
  namespace: external-dns
spec:
  endpoints:
    - dnsName: node.${DOMAIN}
      recordType: A
      recordTTL: 300
      targets:
        - 172.19.149.1
